data:extend({
    {
        type = "module",
        name = "concrete-speed-module",
        icon = "__base__/graphics/icons/speed-module.png",
        icon_size = 64,
        hidden = true,
        subgroup = "module",
        category = "speed",
        tier = 1,
        stack_size = 1,
        effect = { speed = 0.10 },
    },
    {
        type = "module",
        name = "refined-concrete-speed-module",
        icon = "__base__/graphics/icons/speed-module.png",
        icon_size = 64,
        hidden = true,
        subgroup = "module",
        category = "speed",
        tier = 1,
        stack_size = 1,
        effect = { speed = 0.25 },
    },
        {
        type = "module",
        name = "hazard-concrete-prod-module",
        icon = "__base__/graphics/icons/productivity-module.png",
        icon_size = 64,
        hidden = true,
        subgroup = "module",
        category = "productivity",
        tier = 1,
        stack_size = 1,
        effect = { productivity = 0.10 },
    },
    {
        type = "module",
        name = "refined-hazard-concrete-prod-module",
        icon = "__base__/graphics/icons/productivity-module.png",
        icon_size = 64,
        hidden = true,
        subgroup = "module",
        category = "productivity",
        tier = 1,
        stack_size = 1,
        effect = { productivity = 0.25 },
    }
})
